    <form action="<?php echo $action; ?>" method="<?php echo $method; ?>" enctype="multipart/form-data">
        <table>
            <tr>
                <td>
                    <?php echo $username_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $username . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $email_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $email . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $password_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $password . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $file_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $file . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php echo $colors_label . PHP_EOL; ?>
                </td>
                <td>
                    <?php echo $colors . PHP_EOL; ?>
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    <?php echo $submit . PHP_EOL; ?>
                </td>
            </tr>
        </table>
    </form>